### ISSUE TITLE
Error on Anki 2.0.4

### ISSUE THREAD

**Issue by sobjornstad** [Kenishi/Failed-Mature-Cards#1]
Traceback (most recent call last):
  File "/home/soren/code/anki/unstable/anki/aqt/addons.py", line 38, in loadAddons
    **import**(file.replace(".py", ""))
  File "/home/soren/Anki/addons/Failed_Mature_Cards.py", line 98, in 
    anki.stats.CollectionStats.cardGraph = wrap(anki.stats.CollectionStats.cardGraph, failingGraph, pos="")
AttributeError: 'module' object has no attribute 'stats'

Not entirely certain this isn't my fault in some way, but as far as I can tell it started happening when I upgraded to 2.0.4 beta.

**Comment by ghost** [comment]
It's the same for me, just before upgrading everything were working fine, after update have the exact same error
it's the same for my other custom graphs too

from anki forum:

>  Damien Elmes: The addon needs to import anki.stats if it uses anki.stats.

**Comment by sobjornstad** [comment]
I have submitted a pull request that solves the problem (all it needed was an import statement). The change needs to be made on your other custom graph addon as well--I'll let you do that.
